// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cascader: typeof import('./src/components/fields/Cascader.vue')['default']
    Date: typeof import('./src/components/fields/Date.vue')['default']
    DateRange: typeof import('./src/components/fields/DateRange.vue')['default']
    DateTime: typeof import('./src/components/fields/DateTime.vue')['default']
    DateTimeRange: typeof import('./src/components/fields/DateTimeRange.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    Filterbar: typeof import('./src/components/Filterbar.vue')['default']
    FilterbarButtons: typeof import('./src/components/FilterbarButtons.vue')['default']
    FilterbarField: typeof import('./src/components/FilterbarField.vue')['default']
    FilterbarFields: typeof import('./src/components/FilterbarFields.vue')['default']
    Label: typeof import('./src/components/fields/Label.vue')['default']
    ListviewContent: typeof import('./src/components/ListviewContent.vue')['default']
    ListviewContentFooter: typeof import('./src/components/ListviewContentFooter.vue')['default']
    ListviewHeader: typeof import('./src/components/ListviewHeader.vue')['default']
    ListviewLayout: typeof import('./src/components/ListviewLayout.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MessageBlock: typeof import('./src/components/MessageBlock.vue')['default']
    MultipleSelect: typeof import('./src/components/fields/MultipleSelect.vue')['default']
    Number: typeof import('./src/components/fields/Number.vue')['default']
    Select: typeof import('./src/components/fields/Select.vue')['default']
    StoreProvider: typeof import('./src/components/StoreProvider.vue')['default']
    Text: typeof import('./src/components/fields/Text.vue')['default']
    TimePicker: typeof import('./src/components/fields/TimePicker.vue')['default']
    TimePickerRange: typeof import('./src/components/fields/TimePickerRange.vue')['default']
    TimeSelect: typeof import('./src/components/fields/TimeSelect.vue')['default']
  }
}

export {}
