// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    FieldCascader: typeof import('./src/components/fields/FieldCascader.vue')['default']
    FieldDate: typeof import('./src/components/fields/FieldDate.vue')['default']
    FieldDateRange: typeof import('./src/components/fields/FieldDateRange.vue')['default']
    FieldDateTime: typeof import('./src/components/fields/FieldDateTime.vue')['default']
    FieldDateTimeRange: typeof import('./src/components/fields/FieldDateTimeRange.vue')['default']
    FieldLabel: typeof import('./src/components/fields/FieldLabel.vue')['default']
    FieldMultipleSelect: typeof import('./src/components/fields/FieldMultipleSelect.vue')['default']
    FieldNumber: typeof import('./src/components/fields/FieldNumber.vue')['default']
    FieldSelect: typeof import('./src/components/fields/FieldSelect.vue')['default']
    FieldText: typeof import('./src/components/fields/FieldText.vue')['default']
    FieldTimePicker: typeof import('./src/components/fields/FieldTimePicker.vue')['default']
    FieldTimePickerRange: typeof import('./src/components/fields/FieldTimePickerRange.vue')['default']
    FieldTimeSelect: typeof import('./src/components/fields/FieldTimeSelect.vue')['default']
    Filterbar: typeof import('./src/components/Filterbar.vue')['default']
    FilterbarButtons: typeof import('./src/components/FilterbarButtons.vue')['default']
    FilterbarField: typeof import('./src/components/FilterbarField.vue')['default']
    FilterbarFields: typeof import('./src/components/FilterbarFields.vue')['default']
    ListviewContent: typeof import('./src/components/ListviewContent.vue')['default']
    ListviewContentFooter: typeof import('./src/components/ListviewContentFooter.vue')['default']
    ListviewFilterbar: typeof import('./src/components/ListviewFilterbar.vue')['default']
    ListviewHeader: typeof import('./src/components/ListviewHeader.vue')['default']
    ListviewLayout: typeof import('./src/components/ListviewLayout.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MessageBlock: typeof import('./src/components/MessageBlock.vue')['default']
    StoreProvider: typeof import('./src/components/StoreProvider.vue')['default']
  }
}

export {}
