name: Publish GH Pages

on:
  push:
    branches:
      - master
    tags:
      - v*
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      target_version_path:
        description: 'Specify build to gh-pages version path. (e.g. 2.0)'
        required: false
        default: ''

env:
  TARGET_VERSION_PATH: /

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build the doc
        run: pnpm run docs:build

      - name: Deploy doc
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vitepress/dist # The folder the action should deploy.
          target-folder: ${{ env.TARGET_VERSION_PATH }}
          clean-exclude: version/*
